### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'Afterthought, Version=1.0.8.0

### ISSUE THREAD

**Issue by ch-hristov** [vc3/Afterthought#71]
Hi all , I run Afterthought with the following parameters : 

"$(SolutionDir)......\Packages\Afterthought-forked.1.2.1.0\tools\Afterthought.Amender.exe" -target="$(TargetPath)"

I get :

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Afterthought, Version=1.0.8.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

I'm using https://www.nuget.org/packages/Afterthought-forked/

Why is afterthought searching for another .dll when it should already have it?

**Comment by slicht** [comment]
Just copy the Afterthought.dll from lib to the tools directory. This will solve the problem.
